import ROOT
import numpy as np

histos = dict()

histos['mu1pt'       ] = (ROOT.RDF.TH1DModel('mu1pt'         , '', 50,      0,    40), '#mu_{1} p_{T} (GeV)'                                , 0)
histos['mu2pt'       ] = (ROOT.RDF.TH1DModel('mu2pt'         , '', 50,      0,    20), '#mu_{2} p_{T} (GeV)'                                , 0)
histos['kpt'         ] = (ROOT.RDF.TH1DModel('kpt'           , '', 50,      0,    30), '#mu_{3} p_{T} (GeV)'                                , 0)
histos['mu1phi'      ] = (ROOT.RDF.TH1DModel('mu1phi'        , '', 20, -np.pi, np.pi), '#mu_{1} #phi'                                       , 0)
histos['mu2phi'      ] = (ROOT.RDF.TH1DModel('mu2phi'        , '', 20, -np.pi, np.pi), '#mu_{1} #phi'                                       , 0)
histos['kphi'        ] = (ROOT.RDF.TH1DModel('kphi'          , '', 20, -np.pi, np.pi), '#mu_{1} #phi'                                       , 0)
histos['mu1eta'      ] = (ROOT.RDF.TH1DModel('mu1eta'        , '', 30,     -3,     3), '#mu_{1} #eta'                                       , 0)
histos['mu2eta'      ] = (ROOT.RDF.TH1DModel('mu2eta'        , '', 30,     -3,     3), '#mu_{1} #eta'                                       , 0)
histos['keta'        ] = (ROOT.RDF.TH1DModel('keta'          , '', 30,     -3,     3), '#mu_{1} #eta'                                       , 0)
histos['Bpt'         ] = (ROOT.RDF.TH1DModel('Bpt'           , '', 50,      0,    50), '3#mu p_{T} (GeV)'                                   , 0)
histos['Bmass'       ] = (ROOT.RDF.TH1DModel('Bmass'         , '', 80,      2,     7), '3#mu mass (GeV)'                                    , 0)
histos['Beta'        ] = (ROOT.RDF.TH1DModel('Beta'          , '', 30,     -3,     3), '3#mu eta'                                           , 0)
histos['Bphi'        ] = (ROOT.RDF.TH1DModel('Bphi'          , '', 20, -np.pi, np.pi), '3#mu #phi'                                          , 0)
histos['Bpt_reco'    ] = (ROOT.RDF.TH1DModel('Bpt_reco'      , '', 50,      0,    80), 'corrected 3#mu p_{T} (GeV)'                         , 0)
histos['abs_mu1_dxy' ] = (ROOT.RDF.TH1DModel('mu1_dxy'       , '', 50,      0,   0.2), '#mu_{1} |d_{xy}| (cm)'                              , 1)
histos['mu1_dxy_sig' ] = (ROOT.RDF.TH1DModel('mu1_dxy_sig'   , '', 50,      0,    10), '#mu_{1} |d_{xy}|/#sigma_{d_{xy}}'                   , 1)
histos['abs_mu2_dxy' ] = (ROOT.RDF.TH1DModel('mu2_dxy'       , '', 50,      0,   0.2), '#mu_{2} |d_{xy}| (cm)'                              , 1)
histos['mu2_dxy_sig' ] = (ROOT.RDF.TH1DModel('mu2_dxy_sig'   , '', 50,      0,    10), '#mu_{2} |d_{xy}|/#sigma_{d_{xy}}'                   , 1)
histos['abs_k_dxy'   ] = (ROOT.RDF.TH1DModel('k_dxy'         , '', 50,      0,   0.2), '#mu_{3} |d_{z}| (cm)'                               , 1)
histos['k_dxy_sig'   ] = (ROOT.RDF.TH1DModel('k_dxy_sig'     , '', 50,      0,     1), '#mu_{3} |d_{z}|/#sigma_{d_{z}}'                     , 1)
histos['abs_mu1_dz'  ] = (ROOT.RDF.TH1DModel('mu1_dz'        , '', 50,      0,   0.4), '#mu_{1} |d_{z}| (cm)'                               , 1)
histos['mu1_dz_sig'  ] = (ROOT.RDF.TH1DModel('mu1_dz_sig'    , '', 50,      0,     1), '#mu_{1} |d_{z}|/#sigma_{d_{z}}'                     , 1)
histos['abs_mu2_dz'  ] = (ROOT.RDF.TH1DModel('mu2_dz'        , '', 50,      0,   0.4), '#mu_{2} |d_{z}| (cm)'                               , 1)
histos['mu2_dz_sig'  ] = (ROOT.RDF.TH1DModel('mu2_dz_sig'    , '', 50,      0,     1), '#mu_{2} |d_{z}|/#sigma_{d_{z}}'                     , 1)
histos['abs_k_dz'    ] = (ROOT.RDF.TH1DModel('k_dz'          , '', 50,      0,   0.4), '#mu_{3} |d_{z}| (cm)'                               , 1)
histos['k_dz_sig'    ] = (ROOT.RDF.TH1DModel('k_dz_sig'      , '', 50,      0,     1), '#mu_{3} |d_{z}|/#sigma_{d_{z}}'                     , 1)
histos['Blxy_sig'    ] = (ROOT.RDF.TH1DModel('Blxy_sig'      , '',100,      0,   100), 'L_{xy}/#sigma_{L_{xy}}'                             , 1)
histos['Blxy'        ] = (ROOT.RDF.TH1DModel('Blxy'          , '',100,      0,     2), 'L_{xy} (cm)'                                        , 1)
histos['Blxy_unc'    ] = (ROOT.RDF.TH1DModel('Blxy_unc'      , '',100,      0,   0.5), '#sigma_{L_{xy}} (cm)'                               , 1)
histos['Bsvprob'     ] = (ROOT.RDF.TH1DModel('Bsvprob'       , '', 50,      0,     1), 'vtx(#mu_{1}, #mu_{2}, #mu_{3}) probability'         , 0)
histos['log10_svprob'] = (ROOT.RDF.TH1DModel('Bsvprob'       , '', 51,     -8,     1), 'log_{10} vtx(#mu_{1}, #mu_{2}, #mu_{3}) probability', 1)
histos['Bcos2D'      ] = (ROOT.RDF.TH1DModel('Bcos2D'        , '',100,    0.9,     1), '2D cos#alpha'                                       , 1)
histos['m_miss_sq'   ] = (ROOT.RDF.TH1DModel('m_miss_sq'     , '', 50,      0,    12), 'm^{2}_{miss} (GeV^{2})'                             , 0)
histos['Q_sq'        ] = (ROOT.RDF.TH1DModel('Q_sq'          , '', 50,      0,    12), 'q^{2} (GeV^{2})'                                    , 0)
histos['pt_var'      ] = (ROOT.RDF.TH1DModel('pt_var'        , '', 50,      0,    50), 'p_{T}^{var} (GeV)'                                  , 0)
histos['pt_miss_vec' ] = (ROOT.RDF.TH1DModel('pt_miss_vec'   , '', 50,      0,    50), 'vector p_{T}^{miss} (GeV)'                          , 0)
histos['pt_miss_scal'] = (ROOT.RDF.TH1DModel('pt_miss_scal'  , '', 60,    -10,    50), 'scalar p_{T}^{miss} (GeV)'                          , 0)
histos['E_mu_star'   ] = (ROOT.RDF.TH1DModel('E_mu_star'     , '', 50,      0,   2.5), 'E_{#mu_{3}}* (GeV)'                                 , 0)
histos['E_mu_canc'   ] = (ROOT.RDF.TH1DModel('E_mu_canc'     , '', 50,      0,     6), 'E_{#mu_{3}}^{#} (GeV)'                              , 0)
histos['mu1_mediumID'] = (ROOT.RDF.TH1DModel('mu1_mediumID'  , '',  2,      0,     2), '#mu_{1} mediumID'                                   , 0)
histos['mu2_mediumID'] = (ROOT.RDF.TH1DModel('mu2_mediumID'  , '',  2,      0,     2), '#mu_{2} mediumID'                                   , 0)
histos['k_mediumID'  ] = (ROOT.RDF.TH1DModel('k_mediumID'    , '',  2,      0,     2), '#mu_{3} mediumID'                                   , 0)
histos['mu1_tightID' ] = (ROOT.RDF.TH1DModel('mu1_tightID'   , '',  2,      0,     2), '#mu_{1} tightID'                                    , 0)
histos['mu2_tightID' ] = (ROOT.RDF.TH1DModel('mu2_tightID'   , '',  2,      0,     2), '#mu_{2} tightID'                                    , 0)
histos['k_tightID'   ] = (ROOT.RDF.TH1DModel('k_tightID'     , '',  2,      0,     2), '#mu_{3} tightID'                                    , 0)
histos['mu1_softID'  ] = (ROOT.RDF.TH1DModel('mu1_softID'    , '',  2,      0,     2), '#mu_{1} softID'                                     , 0)
histos['mu2_softID'  ] = (ROOT.RDF.TH1DModel('mu2_softID'    , '',  2,      0,     2), '#mu_{2} softID'                                     , 0)
histos['k_softID'    ] = (ROOT.RDF.TH1DModel('k_softID'      , '',  2,      0,     2), '#mu_{3} softID'                                     , 0)
histos['b_iso03'     ] = (ROOT.RDF.TH1DModel('b_iso03'       , '', 50,      0,    20), '3-#mu I^{abs}_{R=0.3}'                              , 0)
histos['b_iso04'     ] = (ROOT.RDF.TH1DModel('b_iso04'       , '', 50,      0,    20), '3-#mu I^{abs}_{R=0.4}'                              , 0)
histos['k_iso03'     ] = (ROOT.RDF.TH1DModel('k_iso03'       , '', 50,      0,    20), '#mu_{3} I^{abs}_{R=0.3}'                            , 0)
histos['k_iso04'     ] = (ROOT.RDF.TH1DModel('k_iso04'       , '', 50,      0,    20), '#mu_{3} I^{abs}_{R=0.3}'                            , 0)
histos['l1_iso03'    ] = (ROOT.RDF.TH1DModel('l1_iso03'      , '', 50,      0,    20), '#mu_{1} I^{abs}_{R=0.3}'                            , 0)
histos['l1_iso04'    ] = (ROOT.RDF.TH1DModel('l1_iso04'      , '', 50,      0,    20), '#mu_{1} I^{abs}_{R=0.3}'                            , 0)
histos['l2_iso03'    ] = (ROOT.RDF.TH1DModel('l2_iso03'      , '', 50,      0,    20), '#mu_{2} I^{abs}_{R=0.3}'                            , 0)
histos['l2_iso04'    ] = (ROOT.RDF.TH1DModel('l2_iso04'      , '', 50,      0,    20), '#mu_{2} I^{abs}_{R=0.3}'                            , 0)
histos['b_iso03_rel' ] = (ROOT.RDF.TH1DModel('b_iso03_rel'   , '', 50,      0,     2), '3-#mu I^{rel}_{R=0.3}'                              , 0)
histos['b_iso04_rel' ] = (ROOT.RDF.TH1DModel('b_iso04_rel'   , '', 50,      0,     2), '3-#mu I^{rel}_{R=0.4}'                              , 0)
histos['k_iso03_rel' ] = (ROOT.RDF.TH1DModel('k_iso03_rel'   , '', 50,      0,     2), '#mu_{3} I^{rel}_{R=0.3}'                            , 0)
histos['k_iso04_rel' ] = (ROOT.RDF.TH1DModel('k_iso04_rel'   , '', 50,      0,     2), '#mu_{3} I^{rel}_{R=0.3}'                            , 0)
histos['l1_iso03_rel'] = (ROOT.RDF.TH1DModel('l1_iso03_rel'  , '', 50,      0,     2), '#mu_{1} I^{rel}_{R=0.3}'                            , 0)
histos['l1_iso04_rel'] = (ROOT.RDF.TH1DModel('l1_iso04_rel'  , '', 50,      0,     2), '#mu_{1} I^{rel}_{R=0.3}'                            , 0)
histos['l2_iso03_rel'] = (ROOT.RDF.TH1DModel('l2_iso03_rel'  , '', 50,      0,     2), '#mu_{2} I^{rel}_{R=0.3}'                            , 0)
histos['l2_iso04_rel'] = (ROOT.RDF.TH1DModel('l2_iso04_rel'  , '', 50,      0,     2), '#mu_{2} I^{rel}_{R=0.3}'                            , 0)
histos['Bcharge'     ] = (ROOT.RDF.TH1DModel('Bcharge'       , '',  3,     -1,     2), 'B charge'                                           , 0)
histos['mll_raw'     ] = (ROOT.RDF.TH1DModel('mll_raw'       , '', 50,    2.5,   3.5), 'm(#mu_{1}, #mu_{2}) (GeV)'                          , 0)
histos['DR_mu1mu2'   ] = (ROOT.RDF.TH1DModel('DR_mu1mu2'     , '', 50,      0,   1.2), '#DeltaR(#mu_{1}, #mu_{2})'                          , 0)
histos['jpsi_chi2'   ] = (ROOT.RDF.TH1DModel('jpsi_chi2'     , '', 80,      0,  20. ), 'vtx(#mu_{1}, #mu_{2}) #chi^{2}'                     , 0)
histos['Bchi2'       ] = (ROOT.RDF.TH1DModel('b_chi2'        , '', 80,      0,  35. ), 'vtx(#mu_{1}, #mu_{2}, #mu_{3}) #chi^{2}'            , 0)
histos['jpsi_mass'   ] = (ROOT.RDF.TH1DModel('jpsi_mass'     , '', 50,    2.5,   3.5), 'm(#mu_{1}, #mu_{2}) (GeV)'                          , 0)
histos['dr12'        ] = (ROOT.RDF.TH1DModel('dr12'          , '', 50,      0,   1.2), '#DeltaR(#mu_{1}, #mu_{2})'                          , 0)
histos['dr13'        ] = (ROOT.RDF.TH1DModel('dr13'          , '', 50,      0,   1.2), '#DeltaR(#mu_{1}, #mu_{3})'                          , 0)
histos['dr23'        ] = (ROOT.RDF.TH1DModel('dr23'          , '', 50,      0,   1.2), '#DeltaR(#mu_{2}, #mu_{3})'                          , 0)
histos['dr_jpsi_mu'  ] = (ROOT.RDF.TH1DModel('dr_jpsi_mu'    , '', 50,      0,   1.2), '#DeltaR(J/#Psi, #mu_{3})'                           , 0)
histos['maxdr'       ] = (ROOT.RDF.TH1DModel('maxdr'         , '', 50,      0,   1.2), 'maximum #DeltaR(#mu_{i}, #mu_{j})'                  , 0)
histos['mindr'       ] = (ROOT.RDF.TH1DModel('mindr'         , '', 50,      0,   1.2), 'minimum #DeltaR(#mu_{i}, #mu_{j})'                  , 0)
histos['bdt_mu'      ] = (ROOT.RDF.TH1DModel('bdt_mu'        , '',100,      0,   1. ), 'BDT score #mu'                                      , 1)
histos['bdt_tau'     ] = (ROOT.RDF.TH1DModel('bdt_tau'       , '',100,      0,   1. ), 'BDT score #tau'                                     , 1)
histos['bdt_bkg'     ] = (ROOT.RDF.TH1DModel('bdt_bkg'       , '',100,      0,   1. ), 'BDT score bkg'                                      , 1)
