import ROOT

def create_datacard_pass(label, q2_region, nchannel):

    f_histos = ROOT.TFile.Open('multi_plots/%s/datacards/datacard_pass_%s.root' %(label, q2_region))
    keys = f_histos.GetListOfKeys()
    histos = {}
    for key in keys:
        histos[key.ReadObj().GetName()] = f_histos.Get(key.ReadObj().GetName())

    f= open('multi_plots/%s/datacards/datacard_pass_%s.txt' %(label, q2_region),"w")
    f.write("imax 1 number of channels \n")
    f.write("jmax * number of backgrounds \n")
    f.write("kmax * number of independent systematical uncertainties \n") 
    f.write("--------------------------------------------------------------------------- \n") 
    f.write("shapes *    *  param_ws.root wspace:$PROCESS_$CHANNEL wspace:$PROCESS_$SYSTEMATIC_$CHANNEL \n")
    f.write("--------------------------------------------------------------------------- \n") 
    f.write("bin ch%d\n"%nchannel) 
    f.write("observation %.2f\n"%histos['data_obs'].Integral())

    f.write("----------------------------------------------------------------------------\n") 
    f.write("bin                   ch%d      ch%d      ch%d      ch%d      ch%d      ch%d      ch%d      ch%d      ch%d      ch%d      ch%d \n"%(nchannel,nchannel,nchannel,nchannel,nchannel,nchannel,nchannel,nchannel,nchannel,nchannel,nchannel)) 
    f.write("process           jpsi_mu     jpsi_tau    chic0_mu    chic1_mu    chic2_mu    hc_mu       jpsi_hc     psi2s_mu    psi2s_tau   jpsi_x_mu   fakes\n") 
    f.write("process               1          0           2            3           4           5           6           7          8           9           10 \n") 
    f.write("rate      %.2f        %.2f        %.2f        %.2f         %.2f        %.2f        %.2f        %.2f       %.2f        %.2f        1\n"%(histos['jpsi_mu'].Integral(),histos['jpsi_tau'].Integral(),histos['chic0_mu'].Integral(),histos['chic1_mu' ].Integral(),histos['chic2_mu'].Integral(),histos['hc_mu'].Integral(),histos['jpsi_hc'].Integral(),histos['psi2s_mu'].Integral(),histos['psi2s_tau'].Integral(),histos['jpsi_x_mu'].Integral()))
    f.write("-------------------------------------------------------------------- --------------------\n")

    f.write("ctau               shape      1           1          1            1           1           1           1          1          1           -             -\n")
    f.write("puWeight            shape      1           1          1            1           1           1           1          1          1           1             -\n")
    f.write("bbbfakes  shape      -           -          -            -           -           -           -          -          -           -          1 \n")
    f.write("bglvar_e0  shape      1           1          -            -           -           -           -          -          -           -          -\n")
    f.write("bglvar_e1  shape      1           1          -            -           -           -           -          -          -           -          -\n")
    f.write("bglvar_e2  shape      1           1          -            -           -           -           -          -          -           -          -\n")
    f.write("bglvar_e3  shape      1           1          -            -           -           -           -          -          -           -          -\n")
    f.write("bglvar_e4  shape      1           1          -            -           -           -           -          -          -           -          -\n")
    f.write("bglvar_e5  shape      1           1          -            -           -           -           -          -          -           -          -\n")
    f.write("bglvar_e6  shape      1           1          -            -           -           -           -          -          -           -          -\n")
    f.write("bglvar_e7  shape      1           1          -            -           -           -           -          -          -           -          -\n")
    f.write("bglvar_e8  shape      1           1          -            -           -           -           -          -          -           -          -\n")
    f.write("bglvar_e9  shape      1           1          -            -           -           -           -          -          -           -          -\n")
    #f.write("#bc               lnN            1.3         1.3        1.3          1.3         1.3         1.3        1.3         1.3        1.3         -          -\n")
    f.write("br_chic0_over_mu lnN            -           -           1.15         -            -         -          -           -          -           -           -\n")
    f.write("br_chic1_over_mu lnN             -          -            -           1.15         -         -          -           -          -           -           -\n")
    f.write("br_chic2_over_mu lnN             -          -            -           -           1.15        -         -           -           -           -           -\n")
    f.write("br_hc_over_mu    lnN             -           -           -           -           -           1.15      -           -           -           -           -\n")
    f.write("br_jpsi_hc_over_mu lnN           -           -           -           -           -           -        1.15         -           -           -           -\n")
    f.write("br_psi2s_over_mu lnN             -           -           -           -           -           -         -           1.15         -          -           -\n")
    f.write("br_psi2s_over_tau lnN            -           -           -           -           -           -         -           -           1.15        -           - \n")
    f.write("jpsi_plus_x       lnN            -           -           -           -           -           -           -           -           -         1.3         -\n")
    f.write("fake_rate         lnN            -           -           -           -           -           -           -           -           -          -           1.5\n")
    f.write("muon_id           lnN        1.05       1.05        1.05        1.05        1.05        1.05        1.05        1.05         1.05       1.05             -\n")
    f.write("sfReco           shape        1       1        1        1        1        1        1        1         1       1             -\n")
    f.write("sfId           shape        1       1        1        1        1        1        1        1         1       1             -\n")
    f.write("trigger           lnN           1.05        1.05        1.05        1.05        1.05        1.05        1.05        1.05         1.05       1.05        -\n")
    for i in range(1,histos['jpsi_x_mu'].GetNbinsX()+1):
        f.write("bbb"+str(i)+"_"+str(q2_region)+"_pass            shape      -           -          -            -           -           -           -          -          -           1          -\n")
    
    f.write("----------------------------------------------------------------------------\n") 
    f.write("bc rateParam ch%d jpsi_mu 1\n"%nchannel) 
    f.write("bc rateParam ch%d jpsi_tau 1\n"%nchannel) 
    f.write("bc rateParam ch%d chic0_mu 1\n"%nchannel)
    f.write("bc rateParam ch%d chic1_mu 1\n"%nchannel) 
    f.write("bc rateParam ch%d chic2_mu 1\n"%nchannel)
    f.write("bc rateParam ch%d hc_mu 1\n"%nchannel)
    f.write("bc rateParam ch%d jpsi_hc 1\n"%nchannel)
    f.write("bc rateParam ch%d psi2s_mu 1\n"%nchannel)
    f.write("bc rateParam ch%d psi2s_tau 1\n"%nchannel)
    #f.write("#fakes_rp rateParam ch%d fakes 1\n"%nchannel)

    #f.write("#comb_norm rateParam ch%d comb 1\n"%nchannel)
    #f.write("#mis_id_unc lnN - - 1.2 - \n") 
    #f.write("#recoMuon lnN 1.10 1.10 - 1.10 \n") 
    #f.write("#ctau shape 1 1 - - - - - - - - - \n") 
    #f.write("#mc_comb_unc lnN - - - 1.5 \n") 
    #f.write("#ch%d autoMCStats 1\n") 
    f.close()

    f_histos.Close()
    
def create_datacard_fail(label, q2_region, nchannel):

    f_histos = ROOT.TFile.Open('multi_plots/%s/datacards/datacard_fail_%s.root' %(label, q2_region))
    keys = f_histos.GetListOfKeys()
    histos = {}
    for key in keys:
        histos[key.ReadObj().GetName()] = f_histos.Get(key.ReadObj().GetName())

    f= open('multi_plots/%s/datacards/datacard_fail_%s.txt' %(label, q2_region),"w")
    f.write("imax 1 number of channels \n")
    f.write("jmax * number of backgrounds \n")
    f.write("kmax * number of independent systematical uncertainties \n") 
    f.write("--------------------------------------------------------------------------- \n") 
    f.write("shapes *    *  param_ws.root wspace:$PROCESS_$CHANNEL wspace:$PROCESS_$SYSTEMATIC_$CHANNEL \n")
    f.write("--------------------------------------------------------------------------- \n") 
    f.write("bin ch%d\n"%nchannel)
    f.write("observation %.2f\n"%histos['data_obs'].Integral())
    f.write("----------------------------------------------------------------------------\n") 
    f.write("bin                   ch%d      ch%d      ch%d      ch%d      ch%d      ch%d      ch%d      ch%d      ch%d      ch%d      ch%d \n"%(nchannel,nchannel,nchannel,nchannel,nchannel,nchannel,nchannel,nchannel,nchannel,nchannel,nchannel)) 
    f.write("process           jpsi_mu     jpsi_tau    chic0_mu    chic1_mu    chic2_mu    hc_mu       jpsi_hc     psi2s_mu    psi2s_tau   jpsi_x_mu   fakes\n") 
    f.write("process               1          0           2            3           4           5           6           7          8           9           10 \n") 
    f.write("rate      %.2f        %.2f        %.2f        %.2f         %.2f        %.2f        %.2f        %.2f       %.2f        %.2f        1\n"%(histos['jpsi_mu'].Integral(),histos['jpsi_tau'].Integral(),histos['chic0_mu'].Integral(),histos['chic1_mu' ].Integral(),histos['chic2_mu'].Integral(),histos['hc_mu'].Integral(),histos['jpsi_hc'].Integral(),histos['psi2s_mu'].Integral(),histos['psi2s_tau'].Integral(),histos['jpsi_x_mu'].Integral()))
    f.write("-------------------------------------------------------------------- --------------------\n")

    f.write("ctau               shape      1           1          1            1           1           1           1          1          1           -             -\n")
    f.write("puWeight             shape      1           1          1            1           1           1           1          1          1           1             -\n")
    f.write("bglvar_e0  shape      1           1          -            -           -           -           -          -          -           -          -\n")
    f.write("bglvar_e1  shape      1           1          -            -           -           -           -          -          -           -          -\n")
    f.write("bglvar_e2  shape      1           1          -            -           -           -           -          -          -           -          -\n")
    f.write("bglvar_e3  shape      1           1          -            -           -           -           -          -          -           -          -\n")
    f.write("bglvar_e4  shape      1           1          -            -           -           -           -          -          -           -          -\n")
    f.write("bglvar_e5  shape      1           1          -            -           -           -           -          -          -           -          -\n")
    f.write("bglvar_e6  shape      1           1          -            -           -           -           -          -          -           -          -\n")
    f.write("bglvar_e7  shape      1           1          -            -           -           -           -          -          -           -          -\n")
    f.write("bglvar_e8  shape      1           1          -            -           -           -           -          -          -           -          -\n")
    f.write("bglvar_e9  shape      1           1          -            -           -           -           -          -          -           -          -\n")
    #f.write("#bc               lnN            1.3         1.3        1.3          1.3         1.3         1.3        1.3         1.3        1.3         -          -\n")
    f.write("br_chic0_over_mu lnN            -           -           1.15         -            -         -          -           -          -           -           -\n")
    f.write("br_chic1_over_mu lnN             -          -            -           1.15         -         -          -           -          -           -           -\n")
    f.write("br_chic2_over_mu lnN             -          -            -           -           1.15        -         -           -           -           -           -\n")
    f.write("br_hc_over_mu    lnN             -           -           -           -           -           1.15      -           -           -           -           -\n")
    f.write("br_jpsi_hc_over_mu lnN           -           -           -           -           -           -        1.15         -           -           -           -\n")
    f.write("br_psi2s_over_mu lnN             -           -           -           -           -           -         -           1.15         -          -           -\n")
    f.write("br_psi2s_over_tau lnN            -           -           -           -           -           -         -           -           1.15        -           - \n")
    f.write("jpsi_plus_x       lnN            -           -           -           -           -           -           -           -           -         1.3         -\n")
    f.write("sfReco           shape        1       1        1        1        1        1        1        1         1       1             -\n")
    f.write("sfId           shape        1       1        1        1        1        1        1        1         1       1             -\n")
    f.write("muon_id lnN                 0.95        0.95        0.95        0.95        0.95        0.95        0.95        0.95        0.95      0.95         -\n")
    f.write("trigger lnN                 1.05        1.05        1.05        1.05        1.05        1.05        1.05        1.05        1.05         1.05      -\n")
    for i in range(1,histos['jpsi_x_mu'].GetNbinsX()+1):
        f.write("bbb"+str(i)+"_"+str(q2_region)+"_fail            shape      -           -          -            -           -           -           -          -          -           1          -\n")
    #f.write("fake_rate         lnN            -           -           -           -           -           -           -           -           -          -           1.5\n")
    
    f.write("----------------------------------------------------------------------------\n") 
    f.write("----------------------------------------------------------------------------\n") 
    f.write("bc rateParam ch%d jpsi_mu 1\n"%nchannel) 
    f.write("bc rateParam ch%d jpsi_tau 1\n"%nchannel) 
    f.write("bc rateParam ch%d chic0_mu 1\n"%nchannel)
    f.write("bc rateParam ch%d chic1_mu 1\n"%nchannel) 
    f.write("bc rateParam ch%d chic2_mu 1\n"%nchannel)
    f.write("bc rateParam ch%d hc_mu 1\n"%nchannel)
    f.write("bc rateParam ch%d jpsi_hc 1\n"%nchannel)
    f.write("bc rateParam ch%d psi2s_mu 1\n"%nchannel)
    f.write("bc rateParam ch%d psi2s_tau 1\n"%nchannel)
    #f.write("#fakes_rp rateParam ch%d fakes 1\n"%nchannel)

    #f.write("#comb_norm rateParam ch%d comb 1\n"%nchannel)
    #f.write("#mis_id_unc lnN - - 1.2 - \n") 
    #f.write("#recoMuon lnN 1.10 1.10 - 1.10 \n") 
    #f.write("#ctau shape 1 1 - - - - - - - - - \n") 
    #f.write("#mc_comb_unc lnN - - - 1.5 \n") 
    #f.write("#ch%d autoMCStats 1\n"%nchannel) 
    f.write("-----------------------------------------------\n") 
    for i in range(1,histos['data_obs'].GetNbinsX()+1):
        f.write("fakes_bin_ch"+str(nchannel)+"_"+str(i)+"  flatParam \n")
        #f.write("stat_bin"+str(i)+"  flatParam \n")

    f.close()
    f_histos.Close()
